/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package flappybirdinjava;
import java.net.URL;
import java.awt.*;
import javax.swing.*;


public class Main 
{
    
    private static Frame frame;


    public static void main(String[] args) 
    {
        frame = new Frame();
    }

    public static URL getPath(String path) 
    {
        return Main.class.getResource(path); //컴퓨터 자체에 절대경로로 바꿔줌
    }

    public static Frame getFrame() //게임오브젝트에서 프레임을 알려주기 위한 함수
    {
        return frame;
    }
}
